//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexonaAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTransaction
    {
        public long Id { get; set; }
        public string ToEmailAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public int RetryCount { get; set; }
        public bool IsEmailSent { get; set; }
        public bool AppendCLLogo { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
