//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexonaAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendedArticlePledge
    {
        public int Id { get; set; }
        public int PledgeId { get; set; }
        public int ArticleId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
