//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexonaAU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserResetPassword> UserResetPasswords { get; set; }
        public DbSet<EmailTransaction> EmailTransactions { get; set; }
        public DbSet<InstaGramHashTag> InstaGramHashTags { get; set; }
        public DbSet<TwitterHashTag> TwitterHashTags { get; set; }
        public DbSet<DiscussionFollower> DiscussionFollowers { get; set; }
        public DbSet<MemberFriend> MemberFriends { get; set; }
        public DbSet<RecommendedArticlePledge> RecommendedArticlePledges { get; set; }
        public DbSet<TractionEmail> TractionEmails { get; set; }
        public DbSet<PledgeInviteData> PledgeInviteDatas { get; set; }
        public DbSet<YouTubeVideo> YouTubeVideos { get; set; }
    }
}
