//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexonaAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class TractionEmail
    {
        public decimal Id { get; set; }
        public string EmailType { get; set; }
        public string TractionQueryString { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
        public bool IsSent { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int RetryCount { get; set; }
    }
}
