//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexonaAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterHashTag
    {
        public int Id { get; set; }
        public string UniqueId { get; set; }
        public string UserName { get; set; }
        public string Post { get; set; }
        public string PostUrl { get; set; }
        public string MediaUrl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Likes { get; set; }
        public string Location { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ScreeName { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
