//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexonaAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class YouTubeVideo
    {
        public long Id { get; set; }
        public int NodeId { get; set; }
        public string NiceUrl { get; set; }
        public string YouTubeVideoId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public long VideoLikes { get; set; }
    }
}
